/*$file${.::Zumo.ino} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: Zumo_v4.qm
* File:  ${.::Zumo.ino}
*
* This code has been generated by QM 4.5.0 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::Zumo.ino} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpn.h" // QP-nano framework
#include "Arduino.h" // Arduino API

#include <Wire.h>
#include <Zumo32U4.h>

//============================================================================
// declare all AO classes...
/*$declare${AOs::Zumo} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

//rechneronline.de/funktionsgraphen/
/*${AOs::Zumo} .............................................................*/
typedef struct Zumo {
/* protected: */
    QActive super;

/* private: */
    uint8_t leftProx;
    uint8_t rightProx;
    uint16_t leftSpeed;
    uint16_t rightSpeed;
} Zumo;

/* private: */
static uint16_t Zumo_speed(Zumo * const me);

/* protected: */
static QState Zumo_initial(Zumo * const me);
static QState Zumo_hmi(Zumo * const me);
static QState Zumo_proxSens(Zumo * const me);
static QState Zumo_accelerate(Zumo * const me);

//rechneronline.de/funktionsgraphen/
static QState Zumo_drive(Zumo * const me);
static QState Zumo_turn(Zumo * const me);
/*$enddecl${AOs::Zumo} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
//...

// AO instances, other objects and event queue buffers for them...
Zumo AO_Zumo;

// Other objects
Zumo32U4LCD lcd;
Zumo32U4ButtonA buttonA;
Zumo32U4ProxmitySensors proxSensors;
Zumo32U4Motors motors;
// Zumo32U4Encoders encoders;

static QEvt l_zumoQSto[10]; // Event queue storage for Zumo
//...

//============================================================================
// QF_active[] array defines all active object control blocks ----------------
QActiveCB const Q_ROM QF_active[] = {
        {(QActive *)0,        (QEvt *)0,  0U               },
        {(QActive *)&AO_Zumo, l_zumoQSto, Q_DIM(l_zumoQSto)}
};

//============================================================================
// various constants for the application...
enum {
    BSP_TICKS_PER_SEC = 100, // number of system clock ticks in one second

    // https://rechneronline.de/funktionsgraphen/
    // Funktionsgleichung: y = a * (x - d) + e
    aR = -80,  // Steigung für's Regeln
    aA = -133, // Steigung für's Ausweichen
    d = 1U,    // Scheitelpunkt x
    e = 400U,  // Scheitelpunkt y

    turnSpeed = 80U // speed for turning around
};

// various signals for the application...
enum {
    BUTTON_SIG = Q_USER_SIG, // end of data
    DECIDE_SIG
};

//............................................................................
void setup() {
    // initialize the QF-nano framework
    QF_init(Q_DIM(QF_active));

    // initialize all AOs...
    QActive_ctor(&AO_Zumo.super, Q_STATE_CAST(&Zumo_initial));

    proxSensors.initFrontSensor();
}

//............................................................................
void loop() {
    QF_run(); // run the QF-nano framework
}

//============================================================================
// interrupts...
ISR(TIMER4_COMPA_vect) {
    QF_tickXISR(0); // process time events for tick rate 0
}

//============================================================================
// QF callbacks...
void QF_onStartup(void) {
// 1/1024 prescaler, interrupt enabling...
TCCR4B = (1U << CS43) | (1U << CS41) | (1U << CS40); // CK/1024
TIMSK4 = (1U << OCIE4A); // Interrupt enabled

// set the output-compare register based on the desired tick frequency
OCR4A  = (F_CPU / BSP_TICKS_PER_SEC / 1024U) - 1U;
}

//............................................................................
void QV_onIdle(void) {   // called with interrupts DISABLED
    // Put the CPU and peripherals to the low-power mode. You might
    // need to customize the clock management for your application,
    // see the datasheet for your particular AVR MCU.
    SMCR = (0 << SM0) | (1 << SE); // idle mode, adjust to your project
    QV_CPU_SLEEP();  // atomically go to sleep and enable interrupts
}
//............................................................................
void Q_onAssert(char const Q_ROM * const file, int line) {
    // implement the error-handling policy for your application!!!
    QF_INT_DISABLE(); // disable all interrupts
    QF_RESET();  // reset the CPU
}

//============================================================================
// define all AO classes (state machine)...
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 650U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpn version 6.5.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${AOs::Zumo} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/

//rechneronline.de/funktionsgraphen/
/*${AOs::Zumo} .............................................................*/
/*${AOs::Zumo::speed} ......................................................*/
static uint16_t Zumo_speed(Zumo * const me) {
    int16_t a;
    uint8_t prox;

    return a * (prox - d) + e;
}

/*${AOs::Zumo::SM} .........................................................*/
static QState Zumo_initial(Zumo * const me) {
    /*${AOs::Zumo::SM::initial} */
    lcd.print("press A");
    return Q_TRAN(&Zumo_hmi);
}
/*${AOs::Zumo::SM::hmi} ....................................................*/
static QState Zumo_hmi(Zumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Zumo::SM::hmi} */
        case Q_ENTRY_SIG: {
            if (buttonA.isPressed()) {
                QACTIVE_POST((QActive *)me,
                BUTTON_SIG, 0);
                lcd.clear();
                }

            QActive_armX((QActive *)me,
                0U, BSP_TICKS_PER_SEC, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Zumo::SM::hmi} */
        case Q_EXIT_SIG: {
            QActive_disarmX((QActive *)me, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Zumo::SM::hmi::BUTTON} */
        case BUTTON_SIG: {
            status_ = Q_TRAN(&Zumo_proxSens);
            break;
        }
        /*${AOs::Zumo::SM::hmi::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Zumo_hmi);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Zumo::SM::hmi::proxSens} ..........................................*/
static QState Zumo_proxSens(Zumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Zumo::SM::hmi::proxSens} */
        case Q_ENTRY_SIG: {
            proxSensors.read();
            me->leftProx =
                proxSensors.countsFrontWithLeftLeds();
            me->rightProx =
                proxSensors.countsFrontWithRightLeds();

            QACTIVE_POST((QActive *)me, DECIDE_SIG, 0);

            QActive_armX((QActive *)me,
                0U, BSP_TICKS_PER_SEC, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Zumo::SM::hmi::proxSens} */
        case Q_EXIT_SIG: {
            QActive_disarmX((QActive *)me, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Zumo::SM::hmi::proxSens::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Zumo_proxSens);
            break;
        }
        /*${AOs::Zumo::SM::hmi::proxSens::DECIDE} */
        case DECIDE_SIG: {
            /*${AOs::Zumo::SM::hmi::proxSens::DECIDE::[s<=d]} */
            if (me->leftProx <= d
                && me->rightProx <= d)
            {
                /*${AOs::Zumo::SM::hmi::proxSens::DECIDE::[s<=d]::[v<e]} */
                if (me->leftSpeed < e
                    && me->rightSpeed < e)
                {
                    status_ = Q_TRAN(&Zumo_accelerate);
                }
                else {
                    status_ = Q_UNHANDLED();
                }
            }
            /*${AOs::Zumo::SM::hmi::proxSens::DECIDE::[s<2-6]} */
            else if (d < me->leftProx
                     && me->leftProx <= 6
                     && d < me->rightProx
                     && me->rightProx <= 6)
            {
                status_ = Q_TRAN(&Zumo_drive);
            }
            /*${AOs::Zumo::SM::hmi::proxSens::DECIDE::[v<=100]} */
            else if (me->leftSpeed <= 100U
                     && me->rightSpeed <= 100U)
            {
                status_ = Q_TRAN(&Zumo_turn);
            }
            else {
                status_ = Q_UNHANDLED();
            }
            break;
        }
        default: {
            status_ = Q_SUPER(&Zumo_hmi);
            break;
        }
    }
    return status_;
}
/*${AOs::Zumo::SM::hmi::proxSens::accelerate} ..............................*/
static QState Zumo_accelerate(Zumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Zumo::SM::hmi::proxSens::accelerate} */
        case Q_ENTRY_SIG: {
            me->leftSpeed = me->leftSpeed + 50U;
            me->rightSpeed = me->rightSpeed + 50U;

            motors.setSpeeds(me->leftSpeed, me->rightSpeed);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Zumo_proxSens);
            break;
        }
    }
    return status_;
}

//rechneronline.de/funktionsgraphen/
/*${AOs::Zumo::SM::hmi::proxSens::drive} ...................................*/
static QState Zumo_drive(Zumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Zumo::SM::hmi::proxSens::drive} */
        case Q_ENTRY_SIG: {
            me->leftSpeed = a * me->rightProx + e;
            me->rightSpeed = a * me->leftProx + e;

            motors.setSpeeds(me->leftSpeed, me->rightSpeed);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Zumo_proxSens);
            break;
        }
    }
    return status_;
}
/*${AOs::Zumo::SM::hmi::proxSens::turn} ....................................*/
static QState Zumo_turn(Zumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Zumo::SM::hmi::proxSens::turn} */
        case Q_ENTRY_SIG: {
            motors.setSpeeds(TURN_SPEED, 0U);
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Zumo_proxSens);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Zumo} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
//...
