/*$file${.::Zumo.ino} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*
* Model: Zumo.qm
* File:  ${.::Zumo.ino}
*
* This code has been generated by QM 4.5.1 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::Zumo.ino} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
#include "qpn.h" // QP-nano framework
#include "Arduino.h" // Arduino API

#include <Wire.h>
#include <Zumo32U4.h>

//============================================================================
// declare all AO classes...
/*$declare${AOs::Zumo} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${AOs::Zumo} .............................................................*/
typedef struct Zumo {
/* protected: */
    QActive super;

/* private: */
    uint16_t leftSpeed = 0;;
    uint16_t rightSpeed = 0;;
    int32_t collisionDetect = 0;
    uint8_t prox = 0;
} Zumo;

/* protected: */
static QState Zumo_initial(Zumo * const me);
static QState Zumo_start(Zumo * const me);
static QState Zumo_drive_control(Zumo * const me);
static QState Zumo_stopp(Zumo * const me);
static QState Zumo_drive(Zumo * const me);
/*$enddecl${AOs::Zumo} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
//...

// AO instances, other objects and event queue buffers for them...
Zumo AO_Zumo;

// Other objects
Zumo32U4LCD lcd;
Zumo32U4ButtonA buttonA;
Zumo32U4ButtonB buttonB;
Zumo32U4ButtonC buttonC;
Zumo32U4Motors motors;
LSM303 compass;

static QEvt l_zumoQSto[10]; // Event queue storage for Zumo
//...

//============================================================================
// QF_active[] array defines all active object control blocks ----------------
QActiveCB const Q_ROM QF_active[] = {
        {(QActive *)0,        (QEvt *)0,  0U               },
        {(QActive *)&AO_Zumo, l_zumoQSto, Q_DIM(l_zumoQSto)}
};

//============================================================================
// various constants for the application...
enum {
    BSP_TICKS_PER_SEC = 100U, // number of system clock ticks in one second


    // Funktionsgleichung: y = a * x + e
    a =  -50,                 // Steigung für's Regeln
    e = 300U,                 // Scheitelpunkt y
};

// various signals for the application...
enum {
    BUTTONA_SIG = Q_USER_SIG,  // end of data
    BUTTONB_SIG,
    BUTTONC_SIG,
    COLLISION_SIG,
    FREE_SIG,
    BACK_SIG
};

//............................................................................
void setup() {
    // initialize the QF-nano framework
    QF_init(Q_DIM(QF_active));

    // initialize all AOs...
    QActive_ctor(&AO_Zumo.super, Q_STATE_CAST(&Zumo_initial));

    // init the compass for collision detection
    Wire.begin();
    compass.init();
    compass.enableDefault();
}

//............................................................................
void loop() {
    QF_run(); // run the QF-nano framework
}

//============================================================================
// interrupts...
ISR(TIMER4_COMPA_vect) {
    QF_tickXISR(0); // process time events for tick rate 0
}

//============================================================================
// QF callbacks...
void QF_onStartup(void) {
// 1/1024 prescaler, interrupt enabling...
TCCR4B = (1U << CS43) | (1U << CS41) | (1U << CS40); // CK/1024
TIMSK4 = (1U << OCIE4A); // Interrupt enabled
TCNT4  = 0U;

// set the output-compare register based on the desired tick frequency
OCR4A  = (F_CPU / BSP_TICKS_PER_SEC / 1024U) - 1U;
}

//............................................................................
void QV_onIdle(void) { // called with interrupts DISABLED
    // Put the CPU and peripherals to the low-power mode. You might
    // need to customize the clock management for your application,
    // see the datasheet for your particular AVR MCU.
    SMCR = (0 << SM0) | (1 << SE); // idle mode, adjust to your project
    QV_CPU_SLEEP(); // atomically go to sleep and enable interrupts
}
//............................................................................
void Q_onAssert(char const Q_ROM * const file, int line) {
    // implement the error-handling policy for your application!!!
    QF_INT_DISABLE(); // disable all interrupts
    QF_RESET();  // reset the CPU
}

//============================================================================
// define all AO classes (state machine)...
/*$skip${QP_VERSION} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/* Check for the minimum required QP version */
#if (QP_VERSION < 650U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpn version 6.5.0 or higher required
#endif
/*$endskip${QP_VERSION} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
/*$define${AOs::Zumo} vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv*/
/*${AOs::Zumo} .............................................................*/
/*${AOs::Zumo::SM} .........................................................*/
static QState Zumo_initial(Zumo * const me) {
    /*${AOs::Zumo::SM::initial} */
    lcd.clear();
    lcd.print("set C&B");
    lcd.gotoXY(0, 1);
    lcd.print("press A");
    return Q_TRAN(&Zumo_start);
}
/*${AOs::Zumo::SM::start} ..................................................*/
static QState Zumo_start(Zumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Zumo::SM::start} */
        case Q_ENTRY_SIG: {
            if (buttonA.getSingleDebouncedPress()) {
                lcd.clear();
                QACTIVE_POST((QActive *)me,
                BUTTONA_SIG, 0U);
            }

            else if (buttonC.getSingleDebouncedPress()) {
                lcd.clear();
                QACTIVE_POST((QActive *)me,
                BUTTONC_SIG, 0U);
            }

            else if (buttonB.getSingleDebouncedPress()) {
                lcd.clear();
                QACTIVE_POST((QActive *)me,
                BUTTONB_SIG, 0U);
            }

            QActive_armX((QActive *)me,
                0U, BSP_TICKS_PER_SEC / 10U, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Zumo::SM::start::BUTTONC} */
        case BUTTONC_SIG: {
            if (me->prox < 6U) {
                me->prox++;
            }
            else me->prox = 0;

            lcd.print("s ");
            lcd.print(me->prox);
            status_ = Q_TRAN(&Zumo_start);
            break;
        }
        /*${AOs::Zumo::SM::start::BUTTONB} */
        case BUTTONB_SIG: {
            /*
            if (me->collisionDetect <= xyz) {
            */
                me->collisionDetect = me->collisionDetect + 100;
            // }

            lcd.print("cd ");
            lcd.print(me->collisionDetect);
            status_ = Q_TRAN(&Zumo_start);
            break;
        }
        /*${AOs::Zumo::SM::start::BUTTONA} */
        case BUTTONA_SIG: {
            lcd.clear();
            status_ = Q_TRAN(&Zumo_drive_control);
            break;
        }
        /*${AOs::Zumo::SM::start::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Zumo_start);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Zumo::SM::start::drive_control} ...................................*/
static QState Zumo_drive_control(Zumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Zumo::SM::start::drive_control} */
        case Q_ENTRY_SIG: {
            compass.read();

            /*
            uint32_t result = sqrt(sq(compass.a.x) + sq(compass.a.y));

            static uint32_t lastResult;
            if (result > lastResult) {
                lastResult = result;
            }

            lcd.clear();
            lcd.print("r ");
            lcd.print(lastResult);

            if(result > me->collisionDetect) {
                QACTIVE_POST((QActive *)me, COLLISION_SIG, 0U);
            }
            */

            static int32_t lastX;
            if (abs(compass.a.x) > lastX) {
                lastX = abs(compass.a.x);
            }

            static int32_t lastY;
            if (abs(compass.a.y) > lastY) {
                lastY = abs(compass.a.y);
            }

            lcd.clear();
            lcd.gotoXY(0, 0);
            lcd.print("x ");
            lcd.print(lastX);
            lcd.gotoXY(0, 1);
            lcd.print("y ");
            lcd.print(lastY);

            if((abs(compass.a.x) > me->collisionDetect) ||
                (abs(compass.a.y) > me->collisionDetect)) {
                    QACTIVE_POST((QActive *)me, COLLISION_SIG, 0U);
            }
            else {
                QACTIVE_POST((QActive *)me, FREE_SIG, 0U);
            }

            QActive_armX((QActive *)me,
                0U, BSP_TICKS_PER_SEC / 10U, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Zumo::SM::start::drive_control::COLLISION} */
        case COLLISION_SIG: {
            ledRed(1);
            ledYellow(0);
            ledGreen(0);
            status_ = Q_TRAN(&Zumo_stopp);
            break;
        }
        /*${AOs::Zumo::SM::start::drive_control::FREE} */
        case FREE_SIG: {
            ledRed(0);
            ledYellow(0);
            ledGreen(1);
            status_ = Q_TRAN(&Zumo_drive);
            break;
        }
        /*${AOs::Zumo::SM::start::drive_control::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Zumo_drive_control);
            break;
        }
        default: {
            status_ = Q_SUPER(&Zumo_start);
            break;
        }
    }
    return status_;
}
/*${AOs::Zumo::SM::start::drive_control::stopp} ............................*/
static QState Zumo_stopp(Zumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Zumo::SM::start::drive_control::stopp} */
        case Q_ENTRY_SIG: {
            motors.setSpeeds(0, 0);

            QACTIVE_POST((QActive *)me, BACK_SIG, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Zumo::SM::start::drive_control::stopp::BACK} */
        case BACK_SIG: {
            status_ = Q_TRAN(&Zumo_start);
            break;
        }
        default: {
            status_ = Q_SUPER(&Zumo_drive_control);
            break;
        }
    }
    return status_;
}
/*${AOs::Zumo::SM::start::drive_control::drive} ............................*/
static QState Zumo_drive(Zumo * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Zumo::SM::start::drive_control::drive} */
        case Q_ENTRY_SIG: {
            motors.setSpeeds((a * me->prox + e), (a * me->prox + e));
            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&Zumo_drive_control);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Zumo} ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^*/
//...
